### ISSUE TITLE
Port kanagawa variants dragon and lotus into Emacs

### ISSUE THREAD

**Issue by meritamen** [Fabiokleis/kanagawa-emacs#7]
The original [Kanagawa](https://github.com/rebelot/kanagawa.nvim?tab=readme-ov-file) theme for Neovim also has two variants called `dragon` and `lotus`(`wave` has been ported by default in Emacs), how about porting the other two into Emacs as well?

**Comment by Fabiokleis** [comment]
it is great porting ```dragon``` and ```lotus``,` but we gonna have a lot of work by rewriting every color variable for each variant, I think it is worth it to port them. If you have any idea how to start porting those variants I you @meritamen !

**Comment by meritamen** [comment]
I think we can start by porting the `dragon` variant, because `dragon` [reuses](https://github.com/rebelot/kanagawa.nvim/blob/f491b0fe68fffbece7030181073dfe51f45cda81/lua/kanagawa/themes.lua#L201-L295) many of `wave`'s faces, and the faces in `dragon` palette are very close to the ones in wave, so it's easy to tell what face should be replaced in the corresponding position.

**Comment by meritamen** [comment]
Base faces of three variants are [done](https://github.com/meritamen/emacs-kanagawa-theme/blob/main/kanagawa-colors.el), leaving the more troublesome task of defining the specified theme.

**Comment by Fabiokleis** [comment]
ty for porting kanagawa variants @meritamen !
