### ISSUE TITLE
porting kanagawa theme

### ISSUE THREAD

**Issue by Fabiokleis** [Fabiokleis/kanagawa-emacs#9]
Hi @meritamen, in order to MELPA accepts your modifications I was tying to solve some of those warning using `package-lint` and ignoring `no-byte-compile` flag, but I'm not an experienced in lisp and I had a lot trouble trying to rename all files to fit `kanagawa-themes` prefix and also some of functions so I guess could you help me here: https://github.com/melpa/melpa/pull/9162 please.

**Comment by meritamen** [comment]
I'll make time for it.

**Comment by Fabiokleis** [comment]
Hi @meritamen today one of MELPA maintainers commented on my PR, I think you must see his comment it is related to  namespaces for themes variants https://github.com/melpa/melpa/pull/9162#issuecomment-2341390025. Maybe we don't need to change your code.

**Comment by meritamen** [comment]
I know, meanwhile my new PR fixes something else also.

**Comment by Fabiokleis** [comment]
> I agree with what tarsius said, and meanwhile my new PR fixes something else also. He was only commenting to following
> 
> > ```
> > * kanagawa-colors.el -- not in package namespace `kanagawa-themes-`
> > * kanagawa-dragon-theme.el -- not in package namespace `kanagawa-themes-`
> > * kanagawa-lib.el -- not in package namespace `kanagawa-themes-`
> > * kanagawa-lotus-theme.el -- not in package namespace `kanagawa-themes-`
> > * kanagawa-palette.el -- not in package namespace `kanagawa-themes-`
> > * kanagawa-wave-theme.el -- not in package namespace `kanagawa-themes-`
> > ```

there are anything else do wanna commit on your pr ? I'm gonna merge it

**Comment by meritamen** [comment]
So far, no more.

**Comment by meritamen** [comment]
If you're available please go comment that package is already updated. I don't think there's anything wrong with the package now, I've checked with package-lint that there are no issues unless specifically byte compiling `kanagawa-themes.el` produces warnings about unused variables. And, I've been between jobs lately, so I may not have time to help you.

**Comment by Fabiokleis** [comment]
I already message the MELPA maintainer, ty
